### PR TITLE
Beautify `broccoli-middleware`.

### PR DESCRIPTION
**Pull request by kratiahuja**
Addresses this [issue](https://github.com/ember-cli/broccoli-middleware/issues/9).

- [x] Beautify the `lib` directory
- [x] Use eslint instead of jshint 

cc: @stefanpenner

### CODE REVIEW

**Comment by kratiahuja** [comment]
@stefanpenner I would appreciate your help here. I don't know how to fix the tests for Node < 4.x in such a scenario. I am pretty sure i am doing something really silly 😕

**Review by Turbo87 — APPROVED** [review]
Awesome, thanks @kratiahuja! I am a little worried about this causing massive merge conflicts with the 1.x branch, but I guess we have those already anyway.

**Comment by Turbo87** [comment]
Regarding the failing tests: you can use the 2.x branch of eslint for node 0.x support

**Comment by stefanpenner** [comment]
> Awesome, thanks @kratiahuja! I am a little worried about this causing massive merge conflicts with the 1.x branch, but I guess we have those already anyway.

isn't this already the 1x branch? upstream (yet to be extracted): https://github.com/broccolijs/broccoli/blob/master/lib/middleware.js

**Comment by Turbo87** [comment]
> isn't this already the 1x branch?

you are totally correct. `master` is 1.x and `ember-cli` is the 0.x branch.

**Comment by stefanpenner** [comment]
> ember-cli is the 0.x branch.

For note: its pretty simple also to make ember-cli work with this branch. Just requires some changes to the error objects (or maybe a compat layer when providing the errors to the template.

This is likely our path to incrementally getting to 1.0

**Comment by stefanpenner** [comment]
@kratiahuja you will likely need to use a slightly older eslint, the one you have using `=>` which older nodes don't support by default

**Comment by kratiahuja** [comment]
@stefanpenner @Turbo87  Thanks for the hint. Figured the issue was with the version of `mocha-eslint` I was using. This should be good to merge now.

**Pull request merged**
