### PR TITLE
Provide streaming support

### PR DESCRIPTION
**Pull request by landongn**
Second try!

## Changes
- updated the middleware method to detect `Range` header requests
- respond to those requests with the appropriate 206 HTTP response code (see [This definition for the partial content response code](https://httpstatuses.com/206)
- added two tests for a zero based range with no limit and a specific range limit

### CODE REVIEW

**Comment by kratiahuja** [comment]
**Question**: Is this something we want to support out of the box for all ember apps? What's the usecase being solved here?

If not, the better way would be to create an addon once this [RFC](https://github.com/ember-cli/rfcs/pull/80) lands

**Comment by landongn** [comment]
If you deal with audio or video rendering that isn't hosted on a CDN for local development, it's mandatory.  Not serving the appropriate response code and data stream will not allow you to seek or buffer media. 

Why wouldn't this get supported out of the box, considering other responses (like a 400 response code, as well as caching rules) are hardcoded into the serving mechanism?

**Comment by kratiahuja** [comment]
IMO ember-cli should only support a limited set of assets like simple file serving rather than a range of asset types. It gets harder and difficult to catch up with different asset support types as time passes. Once the RFC I mentioned is merged and the related PRs, you could very well do this via an addon.

**Comment by landongn** [comment]
Presuming that PR lands, what do you suppose is the best method for handling this as an addon? As far as i'm aware, hooking into where this needs to be handled (e.g; prior to anything exposed to the public), how is that even possible?

Why does everything need to be an addon, by the way?  If the demand on ember-cli is to provide a "server' to work with, shouldn't that server respond with the appropriate request headers and content encoding as it would in production?  It would certainly cause the developer in question to presume their code is the problem, not with the server itself.  Why not just do the thing here?

**Comment by nathanhammond** [comment]
I'm actually in favor of pushing this into `broccoli-middleware` as presuming that everybody is using Ember CLI is a larger assumption than I would like to make. Further, making broccoli-middleware aware of more mime types and how they need to be served is a good thing. It's a fancy static-file-server, it should do as well as it can.

The other direction I could see this going, and am curious about, is delegating to something which already does static file serving (e.g. [`express.static`](https://expressjs.com/en/starter/static-files.html)) rather than rolling our own server. Our ability to serve static files compatibly to all combinations of systems is not exactly a core part of what we're trying to build here and signs us up for more work than we necessarily care to do. Our primary goal here is to serve the files out of the broccoli temp directory.

**Comment by landongn** [comment]
I personally don't think it makes sense to provide the functionality in the first place if it's not going to behave as a similar express or sails boilerplate would given equivalent files and response handling mechanisms.  The fault isn't of `express.static` as streaming content, by definition, isn't served as a static asset, it's chunked.  

in the (relatively small) world of streaming media support, it's an additional header flag and writing a stream instead of a standard `express` response code.  Where else could it go, in theory?  

(unrelated tangent; why _wouldn't_ ember-cli want to provide barebones express.js support for users? This has always baffled me.)

**Comment by nathanhammond** [comment]
@landongn What I mean to say is that all of [this function](https://github.com/ember-cli/broccoli-middleware/blob/master/lib/middleware.js#L31) is approximately implementing a simplistic static serve. I assume (without any research) that this is a solved problem by _something_ and that we could possibly to use that. (By the way: I'm lumping streaming media content into the static serve bucket, and did in my previous comment as well.) In other words, my curiosity was, "can we make the intricacies of serving files not our problem by adding a dependency?"

**Comment by Turbo87** [comment]
closing due to inactivity

**Pull request closed without merging**
