### PR TITLE
Adjust minimum Node version to 6.x 

### PR DESCRIPTION
**Pull request by astronomersiva**
Necessary for #47.

### CODE REVIEW

**Comment by Turbo87** [comment]
@astronomersiva what's the reason for the `yarn.lock` change?

**Comment by astronomersiva** [comment]
@Turbo87 I ran `yarn` once updating the node version. Will revert that file if you want to.

**Comment by Turbo87** [comment]
yeah, I think that would be good. the `yarn.lock` file update itself is valuable, but seems unrelated to the Node version bump

**Comment by stefanpenner** [comment]
will this also be a major bump or do we consider it safe as a minor?

**Comment by Turbo87** [comment]
@stefanpenner should be a major bump since it's a breaking change for Node 4 users

**Comment by astronomersiva** [comment]
@stefanpenner , @Turbo87, a gentle reminder.

**Comment by stefanpenner** [comment]
thanks for the reminder

**Comment by stefanpenner** [comment]
released as v2.0.0 🎉

**Pull request merged**
