### PR TITLE
Streaming Media support for local file serving

### PR DESCRIPTION
**Pull request by landongn**
Middleware didn't provide a way to serve requests for streaming / buffering of media.   this small little PR looks for the appropriate request headers for that style of request, and will `stream.pipe()` that data to the client when applicable, otherwise falling back to middlewares original static file serving mechanism. 

relevant changes are from L116-L137

### CODE REVIEW

**Comment by nathanhammond** [comment]
This seems good. Can you write some tests to confirm behavior when it receives a range header?

**Comment by rwjblue** [comment]
@kratiahuja - Would you mind reviewing as you have been working in this repo recently?

**Comment by landongn** [comment]
hm, it seems 0.10 is having an issue with those two tests, but i'm not sure why.  Anyone have a thought as to why 0.10 would struggle with the same sort of test setup as the previous tests? 🤔

**Comment by landongn** [comment]
Closing- I had patched against 0.18.0 mistakenly.  This breaks.

**Pull request closed without merging**
