### PR TITLE
Re-styling the error page

### PR DESCRIPTION
**Pull request by twokul**
screen shot 2017-06-04 at 5 13 08 pm

### CODE REVIEW

**Comment by jfelchner** [comment]
@twokul looks good but why not work from #4 ?

**Comment by twokul** [comment]
@jfelchner is there something in particular you wanted to be ported? PR seemed stale and required a rebase. It was easier to just start over tbh. I and my teammates are planning to iterate on errors over time.

**Comment by jfelchner** [comment]
@twokul I believe that PR has been recently rebased.  Regardless as you've realized the main changes are in one file so considering it's basically done and just needs a few tweaks so I'm not sure what you mean by "it would be easier to start over".

**Comment by jfelchner** [comment]
Effectively my opinion is that #4 outlines the plan of where we want the error page to go and that PR, although an MVP is much further down that path than this one and already has buy in.  So unless you see a major problem with something in that PR, I'd like to use that as the starting point rather than coming up with something new.

**Comment by twokul** [comment]
@jfelchner I understand you put a lot of work into it and it helped me quite abit when I was working on the error page, thanks a ton! I don't want your efforts to go to waste ofc so I'm planning to iterate towards what you outlined in #4 and make sure we can the best result possible. The only thing I wanted is to land MVP and iterate over time (my teammates want to contribute as well and landing this would let them contribute too). can we agree on that and proceed? 💪 :shipit:

**Comment by jfelchner** [comment]
Based on some confusion and miscommunication with outstanding PRs, branches, issues and all manner of things which were worked out in Slack, I'm going to merge this bad boy.  Then we'll move toward #4 in later PRs.

**Pull request merged**
