### PR TITLE
Drop Node 0.10 support from appveyor

### PR DESCRIPTION
**Pull request by kratiahuja**
Dropping support in appveyor too. 

cc: @rwjblue

### CODE REVIEW

**Comment by rwjblue** [comment]
Can you update to run in 4 and 6 (that is what ember-cli itself does), since node 0.12 is **finally** no longer supported.

**Comment by rwjblue** [comment]
(We can also drop 0.12 from Travis if you want)

**Comment by kratiahuja** [comment]
Aah sorry I didn't realize 0.12 is also dropped. Fixed both travis and appveyor.

**Comment by rwjblue** [comment]
Wheeeee! Thank you!

**Pull request merged**
